### ISSUE TITLE
Training starts from epoch 0 when using a run recovery object.

### ISSUE THREAD

**Issue by Shruthi42** [microsoft/InnerEye-DeepLearning#206]
When continuing to train from a recovered run, the training run starts again from epoch 0. This has the side effect of causing the the inference run to use the run recovery object instead of the weights from the last epoch on the validation and test datasets.

**Comment by ant0nsc** [comment]
Without supplying an additional `--start_epoch=...` argument, training will start from epoch 0. Documentation says that `start_epoch` must be supplied as well.
