### ISSUE TITLE
Inconsistent model registration if you use the code as submodule

### ISSUE THREAD

**Issue by javier-alvarez** [microsoft/InnerEye-DeepLearning#230]
When you train the model with submodule it looks like this:

•	Environment.yml 
•	model_inference_config.json 
•	innereye-deeplearning/score.py

 

However, when you train a model directly with innereye-deeplearning:

•	Environment.yml 
•	model_inference_config.json 
•	score.py

**Comment by ant0nsc** [comment]
To test: We can download the registered model from the run, and inspect its file structure. 
This should be done after the normal PR build, and after the "train via submodule" build.

**Comment by ant0nsc** [comment]
Additional problem: run_scoring is not present when triggered from submodule.
Once that is fixed, the hack in `submit_for_inference`, where we copy `run_scoring.py`, can be removed
