### ISSUE TITLE
Possibility to run without Azure

### ISSUE THREAD

**Issue by sycured** [microsoft/InnerEye-DeepLearning#242]
It'll be interesting for development purpose to be able to run it entirely on localhost without needing Azure.

In addition, a company without the right to use (specific or any) cloud provider can later be authorized and during this time can use InnerEye

**Comment by ant0nsc** [comment]
The code runs perfectly fine without Azure. We are using runs on local dev boxes for model development and debugging. But of course, to build any reasonably large model, you would need a machine that has a GPU. 
Do let us know if there is anything that absolutely does not work without Azure, but that should work on the local box.

**Comment by ant0nsc** [comment]
I added a sentence to README in #243 that I hope clarifies this. I'll close this issue when the PR goes in - please re-open if you feel there are still questions.
