### ISSUE TITLE
Feature request: Liver segmentation

### ISSUE THREAD

**Issue by MaherJendoubi** [microsoft/InnerEye-DeepLearning#263]
![image](https://user-images.githubusercontent.com/1798510/94771861-8f6bbb00-03b8-11eb-9ce7-33adf1b4eba0.png)

**Comment by ant0nsc** [comment]
We don't have any well curated datasets available for liver segmentation, unfortunately. However, the architecture that we have in the repository are tested both on segmentation tasks for Prostate and Head&Neck cancer, and worked well on both. Hence, we are pretty certain that they will provide an excellent starting point also for liver segmentation.
If you actually have liver segmentation data available, we'd be happy to work with you on fine-tuning an architecture specifically for that task. Feel free to reach out to me directly if you'd like to discuss in detail.
