### ISSUE TITLE
Bool parameters like --train do not validate that the value is a bool

### ISSUE THREAD

**Issue by javier-alvarez** [microsoft/InnerEye-DeepLearning#350]
--train=Train results on --train=False

We should do better validation here and raise ValueError

[AB#3906](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/3906)

**Comment by ant0nsc** [comment]
Can we simplify the parser in the same washup, and interpret "--azureml" as "--azureml=True"? 
- For all boolean arguments that have `False` as their default, it should be valid to write only `--flag_name`, and it would be equivalent to `--flag_name=True`. 
- For all boolean argument that have `True` as their default, it would still be necessary to say `--flag_name=False` if you want to change its value.

**Comment by ant0nsc** [comment]
Changing the parser: `add_args` in `generic_parsing.py`
