### ISSUE TITLE
[Sample classification task] `azure_dataset_id` definition conflict between `GlaucomaPublicExt.py` and `GlaucomaPublic.py`

### ISSUE THREAD

**Issue by JacopoTeneggi** [microsoft/InnerEye-DeepLearning#397]
When following the [sample classification task instructions](https://github.com/microsoft/InnerEye-DeepLearning/blob/main/docs/sample_tasks.md#creating-the-classification-model-configuration) to create the classification model configuration, we are instructed to specify `azure_dataset_id` in the constructor.

In the definition of `GlaucomaPublic`, though, these lines:

https://github.com/microsoft/InnerEye-DeepLearning/blob/eb5f931f200c253f8a3336fcb01cdaa58c6207be/InnerEye/ML/configs/classification/GlaucomaPublic.py#L12-L13

https://github.com/microsoft/InnerEye-DeepLearning/blob/eb5f931f200c253f8a3336fcb01cdaa58c6207be/InnerEye/ML/configs/classification/GlaucomaPublic.py#L23-L39

override the parameter, causing the experiment to fail if the user has not defined a dataset called `glaucoma_public_dataset`.

Expected behavior(s):

- The parameter is not overridden.
or
- Documentation specifies to call the dataset `glaucoma_public_dataset`.

**Comment by ant0nsc** [comment]
Good catch, thanks for reporting! Update coming soon.
