### ISSUE TITLE
Allow redefinition of DATASET_CSV_FILE_NAME

### ISSUE THREAD

**Issue by kh296** [microsoft/InnerEye-DeepLearning#403]
The scans and structures to be used in a training run are specified in an index file, the name of which is given by the variable InnerEye.ML.common.DATASET_CSV_FILE_NAME.  This is hardcoded to dataset.csv.

When trying to improve model performance, it can sometimes be useful to consider only a subset of patients and/or structures.  This can be achieved by overwriting dataset.csv, or by adding a differently named index file and hacking InnerEye/ML/common.py.  It to be nice instead able to set the value of DATASET_CSV_FILE_NAME in the model definition.

**Comment by ant0nsc** [comment]
```
def test_custom_dataset_name(test_output_dirs: OutputFolderForTests) -> None:
    filename = "foo.csv"
    (test_output_dirs.root_dir / filename).write_text("""subject,channel,...
    """)
    config = SegmentationModelBase()
    config.local_dataset = test_output_dirs.root_dir
    config.custom_dataset_name = "foo.csv"
    dataframe = config.read_dataset_if_needed()
    assert dataframe is not None
```

**Comment by kh296** [comment]
I've enabled user definition of the dataset csv file name by allowing the parameter dataset_csv to be set as part of model configuration.  The parameter is initialised to DATASET_CSV_FILE_NAME in [InnerEye/ML/config.py](https://github.com/kh296/InnerEye-DeepLearning/blob/8824d396f48bf9c1a8f2883f5b516d99d73a803b/InnerEye/ML/config.py#L469), then is used to locate the dataset csv file in [InnerEye/ML/config.py](https://github.com/kh296/InnerEye-DeepLearning/blob/8824d396f48bf9c1a8f2883f5b516d99d73a803b/InnerEye/ML/config.py#L659), in [InnerEye/ML/run_ml.py](https://github.com/kh296/InnerEye-DeepLearning/blob/8824d396f48bf9c1a8f2883f5b516d99d73a803b/InnerEye/ML/run_ml.py#L249) and in [InnerEye/ML/utils/ml_util.py](https://github.com/kh296/InnerEye-DeepLearning/blob/8824d396f48bf9c1a8f2883f5b516d99d73a803b/InnerEye/ML/utils/ml_util.py#L78).  I've added a unit test to [Tests/ML/test_config_helpers.py](https://github.com/kh296/InnerEye-DeepLearning/blob/8824d396f48bf9c1a8f2883f5b516d99d73a803b/Tests/ML/test_config_helpers.py#L128).

The above seems to be all that's needed to set custom dataset csv file names for model training.  However, I've seen that DATASET_CSV_FILE_NAME is used for file location in a number of other places, for example [InnerEye/ML/baselines_util.py](https://github.com/kh296/InnerEye-DeepLearning/blob/8824d396f48bf9c1a8f2883f5b516d99d73a803b/InnerEye/ML/baselines_util.py#L70) and [InnerEye/ML/normalize_and_visualize_dataset.py](https://github.com/kh296/InnerEye-DeepLearning/blob/8824d396f48bf9c1a8f2883f5b516d99d73a803b/InnerEye/ML/normalize_and_visualize_dataset.py#L78).

Should I submit a pull request for the changes made, in that they provide the functionality requested in the Issue submission, or should I first try to avoid DATASET_CSV_FILE_NAME being used anywhere, except as a fallback value?

**Comment by ant0nsc** [comment]
@kh296 please do a pull request with the changes you described. As far as I can see now, the other uses of DATASET_CSV_FILE_NAME  are fine. Once I see the PR, I'll be able to see more clearly anyway.
