### ISSUE TITLE
Builds fail non-reproducibly with papermill timeout errors

### ISSUE THREAD

**Issue by ant0nsc** [microsoft/InnerEye-DeepLearning#419]
A noticeable fraction of builds fails with notebook conversion errors, where papermill times out. Can we do something against that? 

[AB#3784](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/3784)

**Comment by Shruthi42** [comment]
#391 disables `test_generate_segmentation_report`, `test_generate_classification_report` and `test_generate_classification_multilabel_report` which were failing with timeout errors on the windows builds and `test_merge_conda` which was causing problems on the linux builds.

**Comment by ant0nsc** [comment]
Closing for now, thanks @Shruthi42 !
