### ISSUE TITLE
illegal memory access after copy.deepcopy(model) when model is on GPU

### ISSUE THREAD

**Issue by wmpauli** [microsoft/InnerEye-DeepLearning#420]
I'm having trouble with the hello world example. 

getting 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: CUDA error: an illegal memory access was encountered
```

In line 217 of method `forward_preserve_state` in `InnerEye/ML/visualizers/model_summary.py`:
```
    if module.is_model_on_gpu():
        inputs = [input_tensor.cuda() for input_tensor in inputs]
```

I traced it backwards and it happens because of the deepcopy in line 56 of `ModelSummary.__init__`:
```
self.model = copy.deepcopy(model)
```

I'm not sure yet why, because there is typically no problem with deep-copying a model, even if it is on GPU. 

Any ideas?

Using these versions:
```
conda env export -n InnerEye | grep torch
  - pytorch
  - pytorch=1.8.0=py3.7_cuda10.2_cudnn7.6.5_0
  - torchvision=0.9.0=py37_cu102
    - pytorch-lightning==1.1.8
    - torchprof==1.3.3
```   

[AB#3800](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/3800)

**Comment by wmpauli** [comment]
note, no problems when I'm trying to run it on a VM w/o a GPU.

**Comment by ant0nsc** [comment]
That's odd. Which version of InnerEye are you using? We upgraded to PyTorch 1.8 on Monday in #411 , and that got rid of some weird memory errors at other places.

**Comment by ant0nsc** [comment]
I can't repro on a VM with 4 Tesla K80 GPUs. Training the `HelloWorld` works fine.

**Comment by ant0nsc** [comment]
FYI, I get exactly the same setup as you:
```
conda env export -n InnerEye | grep torch
  - pytorch
  - pytorch=1.8.0=py3.7_cuda10.2_cudnn7.6.5_0
  - torchvision=0.9.0=py37_cu102
    - pytorch-lightning==1.1.8
    - torchprof==1.3.3
 ```

**Comment by wmpauli** [comment]
Thanks @ant0nsc , I created a new [Standard_NC6](https://docs.microsoft.com/en-us/azure/virtual-machines/nc-series) [DSVM](https://azure.microsoft.com/en-us/services/virtual-machines/data-science-virtual-machines/) with Ubuntu 18.04, and now I don't have that issue anymore either.
