### ISSUE TITLE
Create portal query for outliers is not useful for non InnerEye users

### ISSUE THREAD

**Issue by javier-alvarez** [microsoft/InnerEye-DeepLearning#449]
def create_portal_query_for_outliers(df: pd.DataFrame) -> str:

[AB#3992](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/3992)

**Comment by dumbledad** [comment]
We found this when looking through my work fixing Issue #423 

The code I worked around creates a query for the InnerEye portal. But since the InnerEye portal is internal only such code should not be in the OSS code.

**Comment by ant0nsc** [comment]
Very good point indeed @dumbledad and @javier-alvarez . Sounds like we should kill the whole query story. 
To make the outlier report a bit more useful, maybe print out all columns but the essential ones? For example, if `dataset.csv` contains columns `foo` and `seriesID`, add those two columns to the outlier report in addition to `subjectID`?
