### ISSUE TITLE
The changelog forms a merge bottleneck without adding useful information

### ISSUE THREAD

**Issue by dumbledad** [microsoft/InnerEye-DeepLearning#462]
Currently we have to add a brief description to the [CHANGELOG.md](https://github.com/microsoft/InnerEye-DeepLearning/blob/main/CHANGELOG.md) file before a pull request can be approved and merged into main. This presents a single point of failure for any merge into main. That is OK if the project team is small, or if all pull requests take very little time to clear, but for larger teams with more complex PRs it does not work.

Some companies fix this issue by taking the changelog outside the git repository, others (e.g. [here](https://about.gitlab.com/blog/2018/07/03/solving-gitlabs-changelog-conflict-crisis/)) add it as a hook into the release build process.

I suspect we do not need it at all. GitHub keeps an ordered list of all this project's closed pull requests ([https://github.com/microsoft/InnerEye-DeepLearning/pulls?q=is:pr+is:closed+sort:updated-desc](https://github.com/microsoft/InnerEye-DeepLearning/pulls?q=is:pr+is:closed+sort:updated-desc)) and they provide a detailed log of what changes came with each merge into main, and why those changes were made.

[AB#4044](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/4044)

**Comment by ant0nsc** [comment]
Agreed that there is a high chance of merge conflicts. However, as discussed, we do need a concise summary of changes. We'll keep that as-is.
