### ISSUE TITLE
Value of model_path in upload_model() function of move_model.py incorrect for ensemble models

### ISSUE THREAD

**Issue by kh296** [microsoft/InnerEye-DeepLearning#469]
The upload_model() function of move_model.py uses ([line 73](https://github.com/microsoft/InnerEye-DeepLearning/blob/5c5687bf61067dae3dbda6ec8aa29d57a7ee91b4/InnerEye/Scripts/move_model.py#L73)):

```
model_path=str(model_path / "final_model"
```

This is fine for models trained in a single run, but for models trained with multiple cross-validation splits the model path is:

```
model_path=str(model_path / "final_ensemble_model"
```

**Comment by ant0nsc** [comment]
Thanks for flagging this. @JonathanTripp , can you take a look?
