### ISSUE TITLE
Training jobs with >1 GPU can get stuck when a DDP process fails

### ISSUE THREAD

**Issue by ant0nsc** [microsoft/InnerEye-DeepLearning#470]
We've seen multiple examples of training jobs in AML where one of the DDP processes fails with an error message, but training still does not terminate. The main process (global rank 0) does not detect that one of the other processes failed, and will keep on waiting for results.

Points to figure out:
* Create a minimum repro for this. It is possibly enough to write code that raises a ValueError in a training_step if the rank of the present code is not 0. Check that this does not terminate in AML.
* Check if upgrade to latest PL and PyTorch fixes the issue
* Check what the behaviour of that repro is when executing outside AML. I would expect it is the same (training does not terminate). 
* File a bug with PyTorch Lightning
* Attempt a hacky fix until PL bug is fixed. In our code, we could have an outermost try/catch. If that catches an exception on any rank other than 0, then attempt to do `RUN_CONTEXT.cancel()`

**Comment by ant0nsc** [comment]
https://github.com/PyTorchLightning/pytorch-lightning/issues/8130

**Comment by melanibe** [comment]
This is actually not fixed in PyTorchLightning/pytorch-lightning#8130 unfortunately.

**Comment by peterhessey** [comment]
Closed as no more evidence of this occurring recently since upgrading pytorch lightning version.

**Comment by riyaj8888** [comment]
i am facing the issue of training got stucked with following  message


```
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
```

**Comment by riyaj8888** [comment]
how can i use all gpus with out stucking
