### ISSUE TITLE
Export in 3D?

### ISSUE THREAD

**Issue by eskeyaar** [microsoft/InnerEye-DeepLearning#480]
Hi,
Once we have segmented the CT scans, can we export the selected segmented in 3D file format either in stl or any other formats?
Also for input, we can use dicom? But why it has to be converted into dicOM-RT to NIFTI? 

Thanks
Santosh 

[AB#4097](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/4097)

**Comment by ant0nsc** [comment]
Your trained model will write its predictions on the test set out in Nifti format (.nii or .nii.gz files). If you search the web, there are a few threads that mention conversion from Nifti to STL, but we are not providing any such conversion.

Yes, you can use Dicom. Please see the [documentation](docs/creating_dataset.md) for how to do that.

**Comment by ant0nsc** [comment]
I'll close this issue now - please re-open if you need any more information.
