### ISSUE TITLE
"XIO:  fatal IO error 25 (Inappropriate ioctl for device) on X server ":0"" in the testing stage of HelloWorld model

### ISSUE THREAD

**Issue by hankuipeng** [microsoft/InnerEye-DeepLearning#510]
When running "python InnerEye/ML/runner.py --model=HelloWorld" on a local Ubuntu 20.04 machine without GPU, the error "XIO:  fatal IO error 25 (Inappropriate ioctl for device) on X server ":0"" occurred. This was caused by 'pool_outputs' on line 187 of ./InnerEye/ML/model_testing.py. I suspect this only occurs when there is only one testing data sample. The problem was resolved for me when I obtain 'pool_outputs' as:

pool_outputs = evaluate_model_predictions(process_id=0, 
                                       config=config, dataset=ds, results_folder=results_folder) 

[AB#4152](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/4152)

**Comment by ant0nsc** [comment]
Hi @hankuipeng , this does not repro for me unfortunately. Have you tried if the solution listed [here](https://stackoverflow.com/questions/45993879/matplot-lib-fatal-io-error-25-inappropriate-ioctl-for-device-on-x-server-loc) works? At the start of `model_testing.py`, you would add:
```
import matplotlib
matplotlib.use('Agg') 
```

**Comment by hankuipeng** [comment]
> Hi @hankuipeng , this does not repro for me unfortunately. Have you tried if the solution listed [here](https://stackoverflow.com/questions/45993879/matplot-lib-fatal-io-error-25-inappropriate-ioctl-for-device-on-x-server-loc) works? At the start of `model_testing.py`, you would add:
> 
> ```
> import matplotlib
> matplotlib.use('Agg') 
> ```

Hi, thanks for your reply, this solves the problem also :)
