### ISSUE TITLE
InnerEyeDDPPlugin - unknown issue comment

### ISSUE THREAD

**Issue by awaelchli** [microsoft/InnerEye-DeepLearning#512]
Hi 

Was snooping around in the codebase and found you have a custom [DDPPlugin](https://github.com/microsoft/InnerEye-DeepLearning/blob/c2f0d668e8cefc1c3868de86c62131f38ca2531d/InnerEye/ML/model_training.py#L358) with a comment at the top that there is apparently a bug you have discovered. It is unclear what exactly is causing issues, could you let me know and I will try to help. I see no substantial differences in this custom plugin compared to upstream, except a few lines of hydra specifc code missing. Is it possible the original problem you encountered is already solved in Lighting 1.3+?

[AB#4155](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/4155)

**Comment by ant0nsc** [comment]
Hey @awaelchli, thanks for checking! Looking that latest code, it appears indeed that the problem is solved in 1.3+. FYI, the original issue is described in #437 , it broke multi-node training. We'll check if we can update easily.

**Comment by ant0nsc** [comment]
done
