### ISSUE TITLE
Documented flag `no-train` does not seem to exist

### ISSUE THREAD

**Issue by dumbledad** [microsoft/InnerEye-DeepLearning#518]
The documentation mentions the `no_train` parameter, i.e. in [here](https://github.com/microsoft/InnerEye-DeepLearning/blob/main/docs/building_models.md#testing-an-existing-model), but there is no mention of that flag in the code. (N.B. the flag is also inconsistently using hyphen when others use underscore).

[AB#4191](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/4191)

**Comment by JonathanTripp** [comment]
In the class `GenericConfig` there is a function `add_boolean_argument` that has special handling for boolean arguments. If the default is True then this creates two exclusive argument options: --flag=True|False or --no-flag. The hyphen may be unusual for this project but it will be standard in argparser 3.8 onwards. See: https://docs.python.org/3/library/argparse.html where the statement

```
parser.add_argument('--foo', action=argparse.BooleanOptionalAction)
```

produces `--no-foo`

**Comment by ant0nsc** [comment]
by design
