### ISSUE TITLE
Find a DataSet for testing

### ISSUE THREAD

**Issue by hossa95** [microsoft/InnerEye-DeepLearning#552]
Hello All, 

I want to test this toll and see it's capabilities. where can I find a decent dataset for testing. 

thanks.  

[AB#4379](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/4379)

**Comment by Shruthi42** [comment]
Hi @hossa95 our [documentation](https://github.com/microsoft/InnerEye-DeepLearning/blob/main/docs/sample_tasks.md) lists two recommended sample tasks that use public datasets.
