### ISSUE TITLE
Should `sphinx-docs/build` and `sphinx-docs/source/md` be ignored?

### ISSUE THREAD

**Issue by JacopoTeneggi** [microsoft/InnerEye-DeepLearning#690]
Hi!

I started to look into #660 , #661 and ran `make html` from `sphinx-docs`. It appears that #660 has been fixed? I was able to reproduce the warning messages in #661 . 

I noticed that the folders `sphinx-docs/build` and `sphinx-source/md`, which are generated by the `make` command, are not ignored. Instead, this folder is ignored 
https://github.com/microsoft/InnerEye-DeepLearning/blob/8a78ec8c1e20e1f20ae551bbf21d6e9cd05f891c/.gitignore#L86-L87
should this be changed?

[AB#5206](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/5206)

**Comment by fepegar** [comment]
You're right. It looks like we should ignore `sphinx-docs/build` and `sphinx-docs/source/md`.
