### ISSUE TITLE
What is `GeoPol.xml`?

### ISSUE THREAD

**Issue by fepegar** [microsoft/InnerEye-DeepLearning#716]
I have noticed this file in this repo (but not on [hi-ml](https://github.com/microsoft/hi-ml)). What does it do? Can we get rid of it?

[AB#5494](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/5494)

**Comment by ant0nsc** [comment]
No, we can't - this is for an MS internal pipeline that checks naming policies.

**Comment by fepegar** [comment]
Is it ok that we don't have it in hi-ml then?
