### ISSUE TITLE
Which paper is referenced in HeadAndNeckBase.py?

### ISSUE THREAD

**Issue by davidkvcs** [microsoft/InnerEye-DeepLearning#730]
Hello

In [HeadAndNeckBase.py](https://github.com/microsoft/InnerEye-DeepLearning/blob/main/InnerEye/ML/configs/segmentation/HeadAndNeckBase.py) the following is stated in a comment:
"with the appropriate dataset, this would build the model whose results are reported in the InnerEye team’s paper".

I assume you mean the follwing paper?
[1] O. Oktay et al., “Evaluation of Deep Learning to Augment Image-Guided Radiotherapy for Head and Neck and Prostate Cancers,” JAMA Netw. Open, pp. 1–11, 2020, doi: 10.1001/jamanetworkopen.2020.27426.

Thank you in advance.

[AB#6005](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/6005)

**Comment by ant0nsc** [comment]
Yes, that is correct. Adding @peterhessey to maybe update the documentation.
