### ISSUE TITLE
Improve model regression tests for large models

### ISSUE THREAD

**Issue by ant0nsc** [microsoft/InnerEye-DeepLearning#740]
**🚀 Feature**

Weekly training runs of the full ensembles the full-scale Prostate and Head&Neck, with strict model comparison that fails and sends emails if regressions are detected. 

**Motivation**

Re-building our baseline models just last week surfaced errors. Model comparison was not strict enough, using statistical tests, meaning that we don't get clear alarm signals.

[AB#6100](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/6100)

**Comment by peterhessey** [comment]
Required features for the completion of this ticket:

- [ ] A set of regression tests that can be configured to refer to a specific run to be used as the baseline.
- [ ] If the regression tests fall out of a certain range of statistical significance, the build should fail.

Code for the existing regression tests can be found in InnerEye/ML/baselines_util.py

**Comment by peterhessey** [comment]
_Updates after conversion between myself, @ant0nsc, @mebristo on 11/07/22_

Currently the parent jobs running regression testing can succeed even if some of their children jobs fail. Checks are necessary to catch this. The current plan is to create e an Azure DevOps job run that is triggered 12-24 hours after the training run is triggered, get the IDs of the child runs and verify if they succeeded, raising a failure if a failed child run is detected.
