### ISSUE TITLE
Move documentation to Read The Docs

### ISSUE THREAD

**Issue by fepegar** [microsoft/InnerEye-DeepLearning#759]
Now that InnerEye actually has Read The Docs (http://innereye-deeplearning.rtfd.io/), that's probably where all the documentation should go (as opposed to markdown files in this repository).

Symlinks [work](https://github.com/microsoft/hi-ml/blob/main/docs/source/multimodal.md), so files wouldn't need to be moved around, just linked.

[AB#6514](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/6514)

**Comment by peterhessey** [comment]
Picking this up, however as per discussion with @fepegar yesterday docs files _will_ be moved around in order to have only a single documentation folder.
