### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by fepegar** [microsoft/InnerEye-DeepLearning#765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue summary

The [InneryEye WSL docs](https://github.com/microsoft/InnerEye-DeepLearning/blob/main/docs/docs/WSL.md) link in https://github.com/microsoft/InnerEye-DeepLearning/blob/main/docs/environment.md#operating-system is broken.

### What documentation should be provided?

I guess the path should be `/docs/WSL.md`, not `/docs/docs/WSL.md`. I haven't checked other links.

[AB#6699](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/6699)

**Comment by peterhessey** [comment]
Closes in https://github.com/microsoft/InnerEye-DeepLearning/pull/768
