### ISSUE TITLE
CHANGELOG.md is outdated

### ISSUE THREAD

**Issue by peterhessey** [microsoft/InnerEye-DeepLearning#773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue summary

CHANGELOG.md is outdated - it doesn't contain information for the most recent release (v0.4)

### What documentation should be provided?

Either CHANGELOG.md should be updated to correspond to the latest changes, or we should only rely on the automatically-generated changelog made by GitHub on new releases.

[AB#6800](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/6800)

**Comment by ant0nsc** [comment]
At the top of the file, it already says that new releases use auto-generated changelog. Do you think it's better to remove all the old changelog entries in that file to avoid confusion?

**Comment by peterhessey** [comment]
So somehow I managed to miss that, I clearly only gave the CHAGELOG.md a _very_ cursory glance! 

However yes I still think it is worth centralising all the changelogs and removing the CHANGELOG.md file - we could copy the entries in it to one of the previous releases to keep a record of them in the same place as new changes?

**Comment by ant0nsc** [comment]
How about we move the present file to something like "changelog_legacy" or "changelog_up_to_v...", and then remove CHANGELOG.md altogether?
