### ISSUE TITLE
Allow retrieval of passwords from KeyVault for Service Principal access

### ISSUE THREAD

**Issue by peterhessey** [microsoft/InnerEye-DeepLearning#786]
**🚀 Feature**

The [setting up AzureML](https://innereye-deeplearning.readthedocs.io/md/setting_up_aml.html?highlight=service%20principal#step-3-optional-create-a-service-principal-authentication-object) should provide an option to retrieve Service Principal passwords from KeyVault.

**Motivation**

Passwords should not be stored in source code.

**Pitch**

Add a flag to `runner.py` and any other required scripts that allows one to specify a keyvault URI to retrieve a service principal password from.

[AB#6930](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/6930)

**Comment by ant0nsc** [comment]
I would suggest to switch the whole authentication story to use `config.json` like in `hi-ml`. With that, we would already get SP authentication out-of-the-box, with passwords stored in environment variables.
