### ISSUE TITLE
Remove/correct dead TRE links

### ISSUE THREAD

**Issue by peterhessey** [microsoft/InnerEye-DeepLearning#794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue summary

There are references in the documenation to a now non-existent branch of AzureTRE:

o	https://github.com/microsoft/AzureTRE/tree/features/InnerEyeAMLPLDeployment/InnerEyeAMLPLDeployment

These need to be removed or corrected to an active branch.

### What documentation should be provided?

Working links to the TRE

[AB#7144](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/7144)

**Comment by ktakeda1** [comment]
This is the Azure TRE documentation for the InnerEye Workspace Service - https://microsoft.github.io/AzureTRE/tre-templates/workspace-services/inner-eye/
