### ISSUE TITLE
`environment_win.yml` is no longer up-to-date

### ISSUE THREAD

**Issue by peterhessey** [microsoft/InnerEye-DeepLearning#822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue summary

The windows locked environment file hasn't been kept up to date with the latest env changes as all dev work takes place on Linux.

I believe it will be easiest to simply remove this file and allow windows users to create their own environments from `primary_deps.yml`. This is as the locking is most important for Azure jobs which are all Ubuntu and creating the locked windows env each time a package is updated is a pain due to having to switch OS's and deal with line-ending issues etc.

### What documentation should be provided?

Removed `environment_win.yml` file and instructions on how to create your own env on windows from the primary dependencies.

[AB#7986](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/7986)

**Comment by peterhessey** [comment]
@ant0nsc keen to hear your thoughts on this!

**Comment by ant0nsc** [comment]
@peterhessey - agree, let's remove env_win.
